package com.zomato.backend.entity;

import com.zomato.backend.entity.enums.OrderStatus;
import com.zomato.backend.entity.enums.PaymentStatus;
import jakarta.persistence.*;
import lombok.*;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * Represents a customer's food order.
 *
 * Table name: "orders" — "order" is a reserved SQL keyword.
 *
 * Financial breakdown:
 *   subtotal     = sum of all OrderItem.lineTotal
 *   deliveryFee  = flat fee (set at checkout, e.g. ₹30)
 *   totalAmount  = subtotal + deliveryFee
 *
 * Payment:
 *   paymentId    = Razorpay payment/order ID (set after payment initiation)
 *   paymentStatus tracks the payment lifecycle independently of order status.
 *
 * Delivery address is embedded (snapshot) — see {@link DeliveryAddress}.
 */
@Entity
@Table(
    name = "orders",
    indexes = {
        @Index(name = "idx_order_customer",    columnList = "customer_id"),
        @Index(name = "idx_order_restaurant",  columnList = "restaurant_id"),
        @Index(name = "idx_order_status",      columnList = "status"),
        @Index(name = "idx_order_number",      columnList = "order_number", unique = true)
    }
)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Order extends BaseEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // ── Unique human-readable order number ────────────────────────────────────

    /**
     * Human-readable identifier shown in receipts and support tickets.
     * Format: "ORD-{YYYYMMDD}-{6-char-uppercase-alphanumeric}"
     * Example: "ORD-20240831-AB12CD"
     *
     * Generated in OrderService before persist — NOT auto-generated by DB.
     */
    @Column(name = "order_number", nullable = false, unique = true, length = 30)
    private String orderNumber;

    // ── Relationships ──────────────────────────────────────────────────────────

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(
        name = "customer_id",
        nullable = false,
        foreignKey = @ForeignKey(name = "fk_order_customer")
    )
    private User customer;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(
        name = "restaurant_id",
        nullable = false,
        foreignKey = @ForeignKey(name = "fk_order_restaurant")
    )
    private Restaurant restaurant;

    /**
     * Line items. CascadeType.ALL — OrderItems have no life outside their Order.
     * orphanRemoval = true ensures items are deleted if removed from this list.
     */
    @OneToMany(mappedBy = "order", cascade = CascadeType.ALL, orphanRemoval = true)
    @Builder.Default
    private List<OrderItem> orderItems = new ArrayList<>();

    // ── Status ────────────────────────────────────────────────────────────────

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 25)
    @Builder.Default
    private OrderStatus status = OrderStatus.PENDING;

    @Enumerated(EnumType.STRING)
    @Column(name = "payment_status", nullable = false, length = 15)
    @Builder.Default
    private PaymentStatus paymentStatus = PaymentStatus.PENDING;

    // ── Payment ───────────────────────────────────────────────────────────────

    /**
     * Payment method chosen by the customer.
     * Values: "RAZORPAY", "COD" (Cash on Delivery).
     */
    @Column(name = "payment_method", nullable = false, length = 20)
    private String paymentMethod;

    /**
     * Razorpay order/payment ID. Null for COD orders.
     * Set after Razorpay payment initiation (Phase 9).
     */
    @Column(name = "payment_id", length = 100)
    private String paymentId;

    // ── Pricing ───────────────────────────────────────────────────────────────

    @Column(nullable = false, precision = 10, scale = 2)
    private BigDecimal subtotal;

    @Column(name = "delivery_fee", nullable = false, precision = 10, scale = 2)
    @Builder.Default
    private BigDecimal deliveryFee = BigDecimal.ZERO;

    @Column(name = "total_amount", nullable = false, precision = 10, scale = 2)
    private BigDecimal totalAmount;

    // ── Delivery Address (snapshot) ────────────────────────────────────────────

    @Embedded
    private DeliveryAddress deliveryAddress;

    // ── Extra fields ──────────────────────────────────────────────────────────

    @Column(name = "special_instructions", length = 500)
    private String specialInstructions;

    /**
     * Estimated delivery time set by the restaurant when confirming the order.
     * Null until the restaurant confirms.
     */
    @Column(name = "estimated_delivery_time")
    private LocalDateTime estimatedDeliveryTime;

    // ── Convenience helper ─────────────────────────────────────────────────────

    /** Adds an item and sets its back-reference in one step. */
    public void addOrderItem(OrderItem item) {
        item.setOrder(this);
        this.orderItems.add(item);
    }
}
